---
title: "Hypothesis Testing"
format: html
editor: visual
---

## Chi-Squared

```{r}
table(df$sex)
table(df$dx)
```

```{r}
table(df$sex, df$dx)
```

```{r}
chisq.test(table(df$sex, df$dx))
```

```{r}
table(df$sex, df$abuse)
chisq.test(table(df$sex, df$abuse))

```

```{r}
df <- df %>%
  mutate(abuse = as.factor(abuse))

```

##T-Test

```{r}
t.test(age ~ sex, data = df)
```

```{r}
df <- df %>%
  mutate(
    sex = as.factor(sex),
    abuse = as.factor(abuse)
  )
```

```{r}
t.test(df$age, mu = 30)

```

```{r}
ggplot(df, aes(x = age)) +
  geom_histogram(binwidth = 2, fill = "#69b3a2", alpha = 0.7, color = "white") +
  geom_vline(xintercept = 30, linetype = "dashed", color = "red", size = 1.2) +
  labs(
    title = "Age Distribution",
    x = "Age",
    y = "Frequency"
  ) +
  theme_minimal()
```

People affected by abuse mostly have effects ages 30 and 40.

##ANOVA

```{r}
set.seed(123)
```

```{r}
aov_age_sex <- aov(age ~ sex, data = df)
```

```{r}
summary(aov_age_sex)
```

This shows that there is no significant correlation between sex and age of people affected by abuse.

##Correlation

```{r}
cor.test(df$age, df$scl_gsi, use = "complete.obs")
```

```{r}
ggplot(data = df, aes(x = age, y = scl_gsi)) + 
  geom_point(color = "purple") +
  theme_bw() +
  labs(x = "Participant Age (years)", y = "Global Severity Index (scl_gsi)") +
  stat_smooth(method = lm)

```

There's no real link between age and psychological distress
