---
title: "Working with data"
format: 
html: 
self contained: true
editor: visual
---

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

------------------------------------------------------------------------

```{r}
library(tidyverse)
```

```{r}
library(descr)
```

```{r}
library(knitr)
```

```{r}
library(dplyr)
```

```{r}
library(haven)
```

```{r}
file_path <- file.path("..", "data", "36168-0001-Data.sav")
df <- read_sav(file_path)
```

```{r}
library(descr)
```

DATA TABLE

```{r}
head(df)
```

FREQ

```{r}
freq(as.ordered(df$SEX), plot = FALSE)
```

```{r}
freq(as.ordered(df$SEX), plot = FALSE)
```

This table shows that more female participants went through abuse that men.

```{r}
freq(as.ordered(df$MOODDX), plot = FALSE)
```

This table shows the amount of people with mood disorders and there are more people with than without.

```{r}
freq(as.ordered(df$RACE), plot = FALSE)
```

This table shows the amount of white, black and other races that went through abuse. White participants were shown to be the ones to go through abuse.

```{r}

```
